### ISSUE TITLE
link to regex docs is broken

### ISSUE THREAD

**Issue by BurntSushi** [lpil/rustexp#7]
The canonical link for regex docs is https://docs.rs/regex. Perhaps even better would be to link to the docs for the specific version supported, e.g., https://docs.rs/regex/1.1.9/regex/.

**Comment by lpil** [comment]
Thank you, I guess this was updated at some point.

**Comment by lpil** [comment]
I see there's a PR to fix this. I'll merge and rebuild.

**Comment by BurntSushi** [comment]
Thanks!
