### ISSUE TITLE
Total bikeshed: maybe an easier-to-remember link like `regexp.rs` would be nice?

### ISSUE THREAD

**Issue by ErichDonGubler** [lpil/rustexp#8]
Feel free to close this if this isn't interesting to you. I do, though, because I think you have made something really interesting and it might be worth giving its own domain separate from yours! :)

**Comment by lpil** [comment]
Glad you like it! These little projects used to have their own domains but I got tired of paying for and managing all of them so I've switched to having just one. I'm unlikely to be making any more changes I'm afraid, last time I checked this project doesn't compile anymore. :(
